version: '3.8'

services:
  dashboard:
    build: .
    image: dashboard-app:latest
    container_name: dashboard-app
    ports:
      - "8080:80"
    environment:
      - TZ=Asia/Bangkok
      - GOOGLE_SHEETS_TSV_URL=https://docs.google.com/spreadsheets/d/e/2PACX-1vT5Qu2gRWD_hZX45QY1AyOK0Wl2QEKtR1yjMqQNWWUv7RuAPWwjLCsxsPSp7RcD0HU0tgeiXlwfRMB0/pub?gid=558973433&single=true&output=tsv
    volumes:
      - dashboard_data:/app/dashboard.db
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    labels:
      - "com.dashboard.service=main"
      - "com.dashboard.description=Installation Dashboard Application"

volumes:
  dashboard_data: